### ISSUE TITLE
folder `util` missing

### ISSUE THREAD

**Issue by w3ntao** [coallaoh/WhitenBlackBox#1]
Hi Seong, I'm trying to get your code running but did you forget to upload some utility file? I think the whole folder `util` is missing.

> $ ./run.py
> Traceback (most recent call last):
>   File "./run.py", line 9, in <module>
>     from mnist_nets.train_mnist_nets import main as build_mnist_nets
>   File "src/mnist_nets/train_mnist_nets.py", line 9, in <module>
>     from mnist import training as mnist_train
>   File "src/mnist_nets/mnist.py", line 9, in <module>
>     from imports.ResearchTools import *
>   File "src/imports/ResearchTools.py", line 7, in <module>
>     from util.construct_controls import apply_explist
> ImportError: No module named util.construct_controls

**Comment by coallaoh** [comment]
Hi WentaoZero,

The util package is in ResearchTools submodule. Did you recursively clone this repository?

```bash
git clone https://github.com/coallaoh/WhitenBlackBox.git --recursive
```

**Comment by w3ntao** [comment]
Hi Seong,

Uh that was ... stupid.
With recursively clone, now it's working!

But I couldn't download your pretrained MNIST-NET dataset, even from CISPA (Saarland campus).

Best,
Wentao

**Comment by coallaoh** [comment]
Since the download works for me, can you share the error message when you try
```
wget https://datasets.d2.mpi-inf.mpg.de/joon18iclr/MNIST-NET.tar.gz
```
? (assuming you're using linux machine)
